<?php 
$musik = [
    ['img'=> 'img/music/cupid.png',
  'judul'=>'Cupid',
  'penyanyi'=>'FIFTY FIFTY',
  'lagu'=>'music/cupid.mp3'],
  ['img'=> 'img/music/angelly.jpeg',
  'judul'=>'Angel Like You',
  'penyanyi'=>'Miley Cyrus',
  'lagu'=>'music/angellikeyou.mp3'],
  ['img'=> 'img/music/thoseeyes.jpeg',
  'judul'=>'Those Eyes',
  'penyanyi'=>'New West',
  'lagu'=>'music/thoseeyes.mp3'],
  ['img'=> 'img/music/rightnow.jpg',
  'judul'=>'Right Now',
  'penyanyi'=>'One Direction',
  'lagu'=>'music/rightnow.mp3'],
  ['img'=> 'img/music/sial.jpg',
  'judul'=>'Sial',
  'penyanyi'=>'Mahalini',
  'lagu'=>'music/sial.mp3'],
  ['img'=> 'img/music/taksegampangitu.jpeg',
  'judul'=>'Tak Segampang Itu',
  'penyanyi'=>'Anggi Marito',
  'lagu'=>'music/taksegampangitu.mp3'],
  ['img'=> 'img/music/flower.jpg',
  'judul'=>'FLOWER',
  'penyanyi'=>'JISOO',
  'lagu'=>'music/flower.mp3'],
  ];
  $pop = [
['img'=>'img/music/mesinwaktu.jpeg',
'judul'=>'Mesin Waktu',
'penyanyi'=>'Budi Doremi',
],
['img'=>'img/music/sangdewi.jpeg',
'judul'=>'Sang Dewi',
'penyanyi'=>'Lyodra & Andi Rianto',
],
['img'=>'img/music/takinginusai.jpg',
'judul'=>'Tak Ingin Usai',
'penyanyi'=>'Keisya Levronka',
],
['img'=>'img/music/lantas.jpeg',
'judul'=>'Lantas',
'penyanyi'=>'Juicy Juicy',
],
];
$jpop = [
['img'=>'img/music/shinu.jpeg',
'judul'=>'Shinunoga E-Wa',
'penyanyi'=>'Fujii Kaze',
],
['img'=>'img/music/lemon.png',
'judul'=>'Lemon',
'penyanyi'=>'Kenshi Yonezu',
],
['img'=>'img/music/pretender.png',
'judul'=>'Pretender',
'penyanyi'=>'Official Hige Dandism',
],
['img'=>'img/music/yoru.jpg',
'judul'=>'Yoru ni Kakeru',
'penyanyi'=>'YOASOBI',
],
];
$kpop = [
['img'=>'img/music/flower.jpg',
'judul'=>'Flower',
'penyanyi'=>'FLOWER',
],
['img'=>'img/music/shutdown.jpeg',
'judul'=>'Shut Down',
'penyanyi'=>'BLACKPINK',
],
['img'=>'img/music/seven.jpg',
'judul'=>'손오공',
'penyanyi'=>'SEVENTEEN',
],
['img'=>'img/music/hypeboy.jpg',
'judul'=>'Hype Boy',
'penyanyi'=>'NewJeans',
],
];

$pop = [
    ['img'=>'img/music/mesinwaktu.jpeg',
    'judul'=>'Mesin Waktu',
    'penyanyi'=>'Budi Doremi',
    ],
    ['img'=>'img/music/sangdewi.jpeg',
    'judul'=>'Sang Dewi',
    'penyanyi'=>'Lyodra & Andi Rianto',
    ],
    ['img'=>'img/music/takinginusai.jpg',
    'judul'=>'Tak Ingin Usai',
    'penyanyi'=>'Keisya Levronka',
    ],
    ['img'=>'img/music/lantas.jpeg',
    'judul'=>'Lantas',
    'penyanyi'=>'Juicy Juicy',
    ],
    ];
$jpop = [
    ['img'=>'img/music/shinu.jpeg',
    'judul'=>'Shinunoga E-Wa',
    'penyanyi'=>'Fujii Kaze',
    ],
    ['img'=>'img/music/lemon.png',
    'judul'=>'Lemon',
    'penyanyi'=>'Kenshi Yonezu',
    ],
    ['img'=>'img/music/pretender.png',
    'judul'=>'Pretender',
    'penyanyi'=>'Official Hige Dandism',
    ],
    ['img'=>'img/music/yoru.jpg',
    'judul'=>'Yoru ni Kakeru',
    'penyanyi'=>'YOASOBI',
    ],
    ];
$kpop = [
    ['img'=>'img/music/flower.jpg',
    'judul'=>'Flower',
    'penyanyi'=>'FLOWER',
    ],
    ['img'=>'img/music/shutdown.jpeg',
    'judul'=>'Shut Down',
    'penyanyi'=>'BLACKPINK',
    ],
    ['img'=>'img/music/seven.jpg',
    'judul'=>'손오공',
    'penyanyi'=>'SEVENTEEN',
    ],
    ['img'=>'img/music/hypeboy.jpg',
    'judul'=>'Hype Boy',
    'penyanyi'=>'NewJeans',
    ],
    ];
 ?>