<?php 
$pop = [
    ['img'=>'img/music/mesinwaktu.jpeg',
    'judul'=>'Mesin Waktu',
    'penyanyi'=>'Budi Doremi',
    ],
    ['img'=>'img/music/sangdewi.jpeg',
    'judul'=>'Sang Dewi',
    'penyanyi'=>'Lyodra & Andi Rianto',
    ],
    ['img'=>'img/music/takinginusai.jpg',
    'judul'=>'Tak Ingin Usai',
    'penyanyi'=>'Keisya Levronka',
    ],
    ['img'=>'img/music/lantas.jpeg',
    'judul'=>'Lantas',
    'penyanyi'=>'Juicy Juicy',
    ],
    ];
$jpop = [
    ['img'=>'img/music/shinu.jpeg',
    'judul'=>'Shinunoga E-Wa',
    'penyanyi'=>'Fujii Kaze',
    ],
    ['img'=>'img/music/lemon.png',
    'judul'=>'Lemon',
    'penyanyi'=>'Kenshi Yonezu',
    ],
    ['img'=>'img/music/pretender.png',
    'judul'=>'Pretender',
    'penyanyi'=>'Official Hige Dandism',
    ],
    ['img'=>'img/music/yoru.jpg',
    'judul'=>'Yoru ni Kakeru',
    'penyanyi'=>'YOASOBI',
    ],
    ];
$kpop = [
    ['img'=>'img/music/flower.jpg',
    'judul'=>'Flower',
    'penyanyi'=>'FLOWER',
    ],
    ['img'=>'img/music/shutdown.jpeg',
    'judul'=>'Shut Down',
    'penyanyi'=>'BLACKPINK',
    ],
    ['img'=>'img/music/seven.jpg',
    'judul'=>'손오공',
    'penyanyi'=>'SEVENTEEN',
    ],
    ['img'=>'img/music/hypeboy.jpg',
    'judul'=>'Hype Boy',
    'penyanyi'=>'NewJeans',
    ],
    ];
 ?>